#' nfsa_sto label
#'
#' Labels for sto column  taken from the Matis dictionary
#'
#' @format ## `nfsa_sto_label`
#' \describe{
#'   \item{sto}{code for sto}
#'   \item{sto_label}{label for sto}
#' }
"nfsa_sto_label"

# nfsa_sto_label <-data.frame(
#   stringsAsFactors = FALSE,
#                sto = c("_X","B101","B10K","B11",
#                        "B111","B112","B12","B1G","B1GQ","B1N","B1NQ",
#                        "B2A3G","B2A3N","B2G","B3G","B4G","B4N","B5G","B5GQ",
#                        "B5N","B5NQ","B6G","B6GA","B6N","B7G","B7N","B8G",
#                        "B8N","B9","B9F","B9FX9","B9X9F","BF90","D1","D11",
#                        "D12","D1X61","D2","D21","D211","D212","D214",
#                        "D21X31","D29","D29X39","D3","D31","D39","D4","D4_7",
#                        "D41","D41G","D42","D421","D422","D43","D44",
#                        "D441","D442","D443","D45","D4N","D5","D51","D59",
#                        "D6","D61","D61_NEG","D611","D612","D613","D614",
#                        "D61SC","D62","D63","D631","D632","D7","D71","D72",
#                        "D74","D75","D76","D7N","D8","D9","D91","D92","D99",
#                        "D9N","DIR","EMP","F","IN","IN1","IN2","IN21",
#                        "K","LE","NP","OTE","OTR","P1","P11","P12","P13",
#                        "P1O","P2","P3","P31","P32","P3T5","P4","P41",
#                        "P5","P51C","P51G","P52","P53","P5M","P5M_50K","P6",
#                        "P61","P62","P62F","P7","P71","P72","P72F","POP"),
#          sto_label = c("Unspecified",
#                        "Changes in net worth due to saving and capital transfers",NA,
#                        "External balance of goods and services",
#                        "External balance of goods","External balance of services",
#                        "Current external balance","Value added, gross",
#                        "Gross domestic product at market prices","Value added, net",
#                        "Net domestic product at market prices",
#                        "Operating surplus and mixed income, gross","Operating surplus and mixed income, net",
#                        "Operating surplus, gross","Mixed income, gross",
#                        "Entrepreneurial income (gross)","Entrepreneurial income (net)",
#                        "Balance of primary incomes, gross / National income, gross",
#                        "Gross national income in market prices",
#                        "Balance of primary incomes, net / National income, net",
#                        "Net national income in market prices","Disposable income, gross",
#                        NA,"Disposable income, net",
#                        "Adjusted disposable income, gross","Adjusted disposable income, net",
#                        "Saving, gross","Saving, net","Net lending(+) / net borrowing (-)",
#                        NA,
#                        "Discrepancy between the financial (B9F) and non-financial (B9) net lending/borrowing",NA,
#                        "Net financial assets","Compensation of employees","Wages and salaries",
#                        "Employers- social contributions","D1REC D61NET",
#                        "Taxes on production and imports","Taxes on products",
#                        "Value added type taxes",
#                        "Taxes and duties on imports excluding Value Added Tax",
#                        "Taxes on products except Value Added Tax, import and export taxes",
#                        "Taxes less subsidies on products","Other taxes on production",
#                        "Other taxes on production minus other subsidies on production",
#                        "Subsidies","Subsidies on products",
#                        "Other subsidies on production","Property income","D7REC + D4REC D7PAY  D4PAY",
#                        "Interest","Property income other than interest",
#                        "Distributed income of corporations","Dividends",
#                        "Withdrawals from income of quasi-corporations",
#                        "Reinvested earnings on FDI (Excluding IF)","Other investment income",
#                        "Investment income attributable to insurance policyholders",
#                        "Investment income payable on pension entitlements",
#                        "Investment income attributable to collective investment fund share holders","Rent","Property income other than interest",
#                        "Current taxes on income, wealth, etc.",
#                        "Taxes on income","Other current taxes",
#                        "Social contributions and social benefits","Net social contributions",
#                        "Net social contributions (sign correction for seasonal adjustment)",
#                        "Employers- actual social contributions (secondary income)",
#                        "Employers' imputed social contributions  (secondary income)","Households- actual social contributions",
#                        "Households- social contribution supplements",
#                        "Social insurance scheme service charges (-)",
#                        "Social benefits other than social transfers in kind","Social transfers in kind",
#                        "Social transfers in kind - non-market production",
#                        "Social transfers in kind - purchased market production",
#                        "Other current transfers","Net non-life insurance premiums",
#                        "Non-life insurance claims",
#                        "Current international cooperation","Miscellaneous current transfers",
#                        "Value Added Tax and GNI - based EU own resources",
#                        "Current international cooperation and miscellaneous current transfers",
#                        "Adjustment for the change in pension entitlements",
#                        "Capital transfers","Capital taxes","Investment grants",
#                        "Other capital transfers",
#                        "Other capital transfers and investment grants",NA,"Total employment",
#                        "Transactions in financial assets and liabilities",
#                        "IN=D1_D8,Primary incomes,current transfers and adj.for pens",
#                        "Primary income","Secondary income: current transfers",
#                        "Secondary income: current transfers",
#                        "Changes in positions other than transactions","Closing balance sheet/Positions/Stocks",
#                        "Acquisitions less disposals of non-produced assets",
#                        "Total government expenditure","Total government revenue",
#                        "Output","Market output","Output for own final use",
#                        "Non-market output",
#                        "Market output, output for own final use and payments for other non-market output",
#                        "Intermediate consumption","Final consumption expenditure",
#                        "Individual consumption expenditure",
#                        "Collective consumption expenditure",NA,"Actual final consumption",NA,
#                        "Gross capital formation","Consumption of fixed capital (-)",
#                        "Gross fixed capital formation","Changes in inventories",
#                        "Acquisitions less disposals of valuables",
#                        "Changes in inventories and acquisition less disposals of valuables",
#                        "Changes in inventories and acquisition less disposals of valuables (data correction for seasonal adjustment)",
#                        "Exports of goods and services","Exports of goods",
#                        "Exports of services","Exports of FISIM",
#                        "Imports of goods and services","Imports of goods","Imports of services",
#                        "Imports of FISIM","Population")
# )
#
# usethis::use_data(nfsa_sto_label)
